### ISSUE TITLE
Local activity panic

### ISSUE THREAD

**Issue by wxing1292** [cadence-workflow/cadence-go-client#830]
version 0.9.0

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb325be]

goroutine 2507 [running]:
code.uber.internal/nemo/emobility/vendor/go.uber.org/cadence/internal.(*workflowExecutionContextImpl).retryLocalActivity.func1()
	code.uber.internal/nemo/emobility/vendor/go.uber.org/cadence/internal/internal_task_handlers.go:879 +0x2e
created by time.goFunc
	/root/.uber-go-versions/gimme/versions/go1.12.6.linux.amd64/src/time/sleep.go:169 +0x44
```

**Comment by amuldowney** [comment]
The context is that we were likely querying a workflow that had WORKFLOW_WORKER_UNHANDLED_FAILURE. The reason being non-determinism where a historical activity was changed to a local activity
